server:
  port: 8091
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celeste1110/config-server-nttdata.git
          default-label: main
  profiles:
    active: git
